# Generated by Django 4.2 on 2025-11-23 09:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='touristprofile',
            name='arrival_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='touristprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='touristprofile',
            name='current_location',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='touristprofile',
            name='departure_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='touristprofile',
            name='from_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='touristprofile',
            name='hotel_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='touristprofile',
            name='hotel_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='touristprofile',
            name='nationality',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='touristprofile',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='tourist_photos/'),
        ),
        migrations.AddField(
            model_name='touristprofile',
            name='to_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='touristprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='touristprofile',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.CreateModel(
            name='AuthorityProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('official_email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('agency_type', models.CharField(choices=[('police', 'Police'), ('hospital', 'Hospital/Medical'), ('embassy', 'Embassy'), ('fire', 'Fire Department'), ('tourism', 'Tourism Authority'), ('emergency', 'Emergency Services'), ('other', 'Other')], max_length=50)),
                ('agency_name', models.CharField(max_length=200)),
                ('authority_id', models.CharField(max_length=100, unique=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
